---
Name: silverstripe-cms-alpine
---
SilverStripe\Admin\LeftAndMain:
  extensions:
   - Arillo\Alpine\AlpineExtension

SilverStripe\SiteConfig\SiteConfigLeftAndMain:
  extensions:
   - Arillo\Alpine\AlpineExtension


